stages:
  - prepare
  - build
  - pack
  - deploy

variables:
  GIT_DEPTH: "1"

get_nuget:
  stage: prepare
  tags: 
    - linux
  script:
    - mkdir tools
    - cd tools
    - wget -O nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - cd ..
  artifacts:
    - tools

build_dex:
  stage: build
  dependencies: []
  tags:
    - vs
  script:
    - '.\tools\nuget.exe restore'
    - cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" DataEditorX.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir=$PWD/output/ /p:TargetFrameworkVersion=v4.6'
  artifacts:
    paths:
      - output

pack:
  stage: pack
  dependencies: 
    - build_dex
  tags:
    - linux
  script:
    - mkdir -p dist/releases
    - cd output
    - 7z a -mx9 ../dist/releases/DataEditorX-4.0.0.0.zip ./*
    - cd ..
    - cp DataEditorX/readme.txt dist/version.txt
  artifacts:
    paths:
      - dist/

upload_to_minio:
  stage: deploy
  dependencies:
    - build_dex
  tags: 
    - linux
  script:
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync dist/ s3://mycard/DataEditorX
  only:
    - tags
