stages:
  - prepare
  - build
  - pack
  - deploy

variables:
  GIT_DEPTH: "1"

get_nuget:
  stage: prepare
  tags: 
    - linux
  script:
    - mkdir tools
    - cd tools
    - wget -O nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - cd ..
  artifacts:
    paths:
      - tools

get_data:
  stage: prepare
  tags: 
    - linux
  script:
    - wget -O DataEditorX/data/constant.lua https://cdn02.moecube.com:444/koishipro/contents/script/constant.lua
    - wget -O DataEditorX/data/strings.conf https://cdn02.moecube.com:444/koishipro/contents/strings.conf
  artifacts:
    paths:
      - DataEditorX/data

build_dex:
  stage: build
  dependencies:
    - get_nuget
    - get_data
  tags:
    - vs
  script:
    - '.\tools\nuget.exe restore'
    - cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" DataEditorX.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir=output/ /p:TargetFrameworkVersion=v4.6'
  artifacts:
    paths:
      - output

pack:
  stage: pack
  dependencies: 
    - build_dex
  tags:
    - linux
  script:
    - DEX_VERSION=$(grep -oP '\[DataEditorX\](.+)\[DataEditorX\]' DataEditorX/readme.txt | sed 's/\[DataEditorX\]//g')
    - mkdir -p dist/releases
    - cd output
    - 7z a -mx9 ../dist/releases/DataEditorX-$DEX_VERSION.zip ./*
    - cd ..
    - cp DataEditorX/readme.txt dist/version.txt
  artifacts:
    paths:
      - dist/

upload_to_minio:
  stage: deploy
  dependencies:
    - pack
  tags: 
    - linux
  script:
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync dist/ s3://mycard/DataEditorX
  only:
    - tags
