stages:
  - build
  - deploy
  
variables:
  GIT_DEPTH: "1"

build_dex:
  stage: build
  dependencies: []
  tags:
    - vc-windows
  script:
    - curl -L -o DataEditorX/data/constant.lua https://koishi.pro/ygopro/script/constant.lua
    - curl -L -o DataEditorX/data/strings.conf https://koishi.pro/ygopro/strings.conf
    - rm -rf win32
    - nuget restore
    - msbuild /p:Configuration=Release /p:Platform="Any CPU" /m DataEditorX.sln
    - ren win32 output
    - mkdir -p dist/releases
    - cd output
    - 7z a -mx9 ../dist/releases/DataEditorX-test-vc.zip ./*
    - cd ..
    - cp -rf DataEditorX/readme.txt dist/version.txt
  artifacts:
    paths:
      - dist/

upload_to_minio:
  stage: deploy
  dependencies:
    - build_dex
  tags: 
    - linux
  image: python
  script:
    - pip install -U -i https://mirrors.aliyun.com/pypi/simple/ awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync dist/ s3://mycard/DataEditorX
  only:
    - tags
